var annotated_dup =
[
    [ "forge", "namespaceforge.html", [
      [ "Quaternion", "classforge_1_1_quaternion.html", "classforge_1_1_quaternion" ],
      [ "Random", "classforge_1_1_random.html", "classforge_1_1_random" ],
      [ "Time", "classforge_1_1_time.html", null ],
      [ "Vector2", "classforge_1_1_vector2.html", "classforge_1_1_vector2" ],
      [ "Vector3", "classforge_1_1_vector3.html", "classforge_1_1_vector3" ],
      [ "Vector4", "classforge_1_1_vector4.html", "classforge_1_1_vector4" ]
    ] ],
    [ "irrklang", "namespaceirrklang.html", [
      [ "vec3d", "classirrklang_1_1vec3d.html", null ]
    ] ],
    [ "Ogre", "namespace_ogre.html", [
      [ "Vector", "class_ogre_1_1_vector.html", null ]
    ] ],
    [ "Animator", "class_animator.html", "class_animator" ],
    [ "AudioListener", "class_audio_listener.html", "class_audio_listener" ],
    [ "AudioManager", "class_audio_manager.html", "class_audio_manager" ],
    [ "AudioSource", "class_audio_source.html", "class_audio_source" ],
    [ "Billboard", "class_billboard.html", "class_billboard" ],
    [ "BillboardSet", "class_billboard_set.html", "class_billboard_set" ],
    [ "Button", "class_button.html", "class_button" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "Collider", "class_collider.html", "class_collider" ],
    [ "Component", "class_component.html", "class_component" ],
    [ "ComponentData", "class_component_data.html", "class_component_data" ],
    [ "ContactCallback", "class_contact_callback.html", "class_contact_callback" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "EntityData", "struct_entity_data.html", "struct_entity_data" ],
    [ "Factory", "class_factory.html", "class_factory" ],
    [ "ForgeFunction", "class_forge_function.html", "class_forge_function" ],
    [ "ForgeFunction< void >", "class_forge_function_3_01void_01_4.html", "class_forge_function_3_01void_01_4" ],
    [ "GameLoader", "class_game_loader.html", "class_game_loader" ],
    [ "GUIManager", "class_g_u_i_manager.html", "class_g_u_i_manager" ],
    [ "Image", "class_image.html", "class_image" ],
    [ "Input", "class_input.html", "class_input" ],
    [ "Invoker", "class_invoker.html", "class_invoker" ],
    [ "InvokingForge", "class_invoking_forge.html", "class_invoking_forge" ],
    [ "Light", "class_light.html", "class_light" ],
    [ "LoadManager", "class_load_manager.html", "class_load_manager" ],
    [ "LuaForge", "class_lua_forge.html", "class_lua_forge" ],
    [ "MainForge", "class_main_forge.html", null ],
    [ "Mesh", "class_mesh.html", "class_mesh" ],
    [ "NativeWindowPair", "struct_native_window_pair.html", "struct_native_window_pair" ],
    [ "ParticleSystem", "class_particle_system.html", "class_particle_system" ],
    [ "PhysicsManager", "class_physics_manager.html", "class_physics_manager" ],
    [ "ProgressBar", "class_progress_bar.html", "class_progress_bar" ],
    [ "RectTransform", "class_rect_transform.html", "class_rect_transform" ],
    [ "RenderForge", "class_render_forge.html", "class_render_forge" ],
    [ "RenderManager", "class_render_manager.html", "class_render_manager" ],
    [ "RigidBody", "class_rigid_body.html", "class_rigid_body" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "SceneManager", "class_scene_manager.html", "class_scene_manager" ],
    [ "Sound", "class_sound.html", "class_sound" ],
    [ "SoundGenerator", "class_sound_generator.html", "class_sound_generator" ],
    [ "TestComponent", "class_test_component.html", "class_test_component" ],
    [ "Text", "class_text.html", "class_text" ],
    [ "Transform", "class_transform.html", "class_transform" ],
    [ "UIComponent", "class_u_i_component.html", "class_u_i_component" ]
];